---
- name: install jenkins
  hosts: hosts
  become: yes
  become_method: sudo
  serial: 1
  vars:
#    ansible_user: challenge
    ansible_ssh_private_key_file: /home/bryam_castillo_net/.ssh/id_rsa
  tasks:
    - name: download repo
      get_url:
        url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
        dest: /etc/yum.repos.d/jenkins.repo

    - name: add key
      rpm_key:
        state: present
        key: https://pkg.jenkins.io/redhat/jenkins.io.key

    - name: upgrade
      yum:
        name: '*'
        state: latest

    - name: install
      yum:
        name: jenkins
        state: present

    - name: install java
      yum:
        name: java-11-openjdk-devel
        state: present

    - name: reload system
      systemd:
        daemon_reload: true
        name: jenkins
        state: reloaded
